drop schema if exists master CASCADE;
create schema master;

create table master.market
(
    id   bigint generated by default as identity
        constraint market_pkey
            primary key,
    name varchar(255) not null,
    code varchar(50)  not null
);

create table master.unit_type
(
    id   bigint generated by default as identity
        constraint unit_type_pkey
            primary key,
    name varchar(255) not null,
    code varchar(50)  not null
);

create table master.unit
(
    id                  bigint generated by default as identity
        constraint unit_pkey
            primary key,
    name                varchar(255)             not null,
    internal_short_name varchar(50)              not null,
    internal_long_name  varchar(255)             not null,
    unit_start_date     timestamp with time zone not null,
    unit_end_date       timestamp with time zone,
    unit_type_id        bigint                   not null
        constraint fk_unit_unit_type
            references master.unit_type,
    draft               boolean default true     not null,
    unit_identifier     varchar(255)
);


insert into master.market (name, code)
values ('California ISO', 'CAISO'),
       ('Electric Reliability Council of Texas', 'ERCOT'),
       ('Midcontinent ISO', 'MISO'),
       ('PJM Interconnection', 'PJM'),
       ('New York ISO', 'NY-ISO'),
       ('ISO New England', 'ISO-NE'),
       ('Electric Energy Inc', 'EEI')
;

insert into master.unit_type (name, code)
values ('Battery', 'BAT'),
       ('Combined Cycle Configuration', 'CCC'),
       ('Combustion Turbine', 'CTB'),
       ('Gas Turbine', 'GTB'),
       ('Coal', 'COL'),
       ('Nuclear', 'NUC'),
       ('Solar', 'SOL'),
       ('Wind Turbine', 'WIN'),
       ('Steam Turbine', 'STB');

insert into master.unit(name, internal_short_name, internal_long_name, unit_start_date, unit_end_date, unit_type_id,
                        draft, unit_identifier)

SELECT CONCAT('Unit ', (row_number() over ())::text),
       CONCAT('U', (row_number() over ())::text),
       CONCAT('Unit ', m.code, ' ', (row_number() over ())::text),
       now() - interval '2 years',
       now() + interval '25 years',
       ut.id,
       ut.code <> 'CCC',
       CONCAT(m.code, (row_number() over ()) * ut.id * m.id)
FROM master.market m,
     master.unit_type ut